import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

const profileModal = readFileSync(new URL('../components/pet/PetProfileModal.vue', import.meta.url), 'utf8')

test('PetProfileModal toggles profile fields in place', () => {
  assert.match(profileModal, /isEditingProfile/)
  assert.match(profileModal, /editForm/)
  assert.match(profileModal, /handleStartEdit/)
  assert.match(profileModal, /handleCancelEdit/)
  assert.match(profileModal, /handleSaveEdit/)
  assert.match(profileModal, /formatBirthdayForDateInput/)
  assert.match(profileModal, /h-\[450px\]/)
  assert.match(profileModal, /overflow-y-auto/)
})

test('PetProfileModal edit mode keeps inline field layout', () => {
  assert.match(profileModal, /inlineInputClass/)
  assert.match(profileModal, /rounded-none border-0 border-b/)
  assert.match(profileModal, /focus:ring-0/)
  assert.match(profileModal, /editForm\.weight/)
  assert.match(profileModal, /editForm\.microchipNumber/)
  assert.match(profileModal, /editForm\.neutered/)
  assert.match(profileModal, /editForm\.bloodType/)
  assert.match(profileModal, /editForm\.furColor/)
  assert.match(profileModal, /editForm\.note/)
  assert.doesNotMatch(profileModal, /<form v-else class="min-h-0 min-w-0 space-y-4/)
  assert.doesNotMatch(profileModal, /min-h-\[72px\]/)
})

test('PetProfileModal uses fixed-height select controls for gender and neutered fields', () => {
  assert.match(profileModal, /function normalizeGender/)
  assert.match(profileModal, /gender: normalizeGender\(pet\.gender\)/)
  assert.match(profileModal, /v-model="editForm\.gender"/)
  assert.match(profileModal, /<select[\s\S]*v-model="editForm\.gender"[\s\S]*profileSelectClass/)
  assert.match(profileModal, /<option value="公">公<\/option>/)
  assert.match(profileModal, /<option value="母">母<\/option>/)
  assert.match(profileModal, /<option value="未知">未知<\/option>/)
  assert.match(profileModal, /v-model="editForm\.neutered"/)
  assert.match(profileModal, /<select[\s\S]*v-model="editForm\.neutered"[\s\S]*profileSelectClass/)
  assert.match(profileModal, /<option value="已結紮">已結紮<\/option>/)
  assert.match(profileModal, /<option value="未結紮">未結紮<\/option>/)
  assert.match(profileModal, /appearance-none/)
  assert.doesNotMatch(profileModal, /<option value="male">male<\/option>/)
  assert.doesNotMatch(profileModal, /<option value="female">female<\/option>/)
  assert.doesNotMatch(profileModal, /v-model="editForm\.neutered" type="checkbox"/)
})

test('PetProfileModal name edit field matches profile title sizing', () => {
  assert.match(profileModal, /nameInputClass/)
  assert.match(profileModal, /text-3xl font-bold tracking-wide text-brand-navy/)
  assert.match(profileModal, /`\$\{nameInputClass\} w-full max-w-\[180px\]`/)
  assert.doesNotMatch(profileModal, /-ml-1 w-full max-w-\[220px\] text-2xl/)
})

test('PetProfileModal keeps transparent underline input styling', () => {
  assert.match(profileModal, /text-base font-normal text-brand-darkgray/)
  assert.match(profileModal, /focus:bg-transparent focus:ring-0/)
  assert.match(profileModal, /inlineInputClass/)
  assert.doesNotMatch(profileModal, /rounded-xl border border-slate-200 bg-slate-50\/70/)
})

test('PetProfileModal weight edit field is a text input with kg suffix', () => {
  assert.match(profileModal, /v-model="editForm\.weight"/)
  assert.match(profileModal, /type="text"[\s\S]*v-model="editForm\.weight"/)
  assert.match(profileModal, /v-model="editForm\.weight"[\s\S]*<span>kg<\/span>/)
  assert.match(profileModal, /weightInputStyle/)
  assert.match(profileModal, /class="flex min-w-0 items-center gap-0 text-brand-darkgray"/)
  assert.doesNotMatch(profileModal, /v-model="editForm\.weight"[\s\S]{0,160}type="number"/)
  assert.doesNotMatch(profileModal, /`\$\{inlineInputClass\} w-20`/)
  assert.doesNotMatch(profileModal, /`\$\{detailInputClass\} w-\[4ch\]`/)
})

test('PetProfileModal keeps consistent desktop and mobile layout sizing', () => {
  assert.match(profileModal, /nameInputClass/)
  assert.match(profileModal, /font-bold text-brand-navy/)
  assert.match(profileModal, /const profilePhotoClass =/)
  assert.match(profileModal, /const profileSummaryClass =/)
  assert.match(profileModal, /const profileMetaTextClass =/)
  assert.match(profileModal, /const profileMetaInputClass =/)
  assert.match(profileModal, /const profileBirthdayInputClass =/)
  assert.match(profileModal, /v-if="pet\.age"[\s\S]*formatValue\(pet\.age\)/)
  assert.match(profileModal, /h-36 w-36/)
  assert.match(profileModal, /shrink-0/)
  assert.match(profileModal, /md:h-40 md:w-40/)
  assert.match(profileModal, /grid-cols-1/)
  assert.match(profileModal, /auto-rows-max/)
  assert.match(profileModal, /md:grid-cols/)
  assert.match(profileModal, /md:auto-rows-auto/)
  assert.match(profileModal, /min-h-0[\s\S]*md:min-h-0/)
  assert.match(profileModal, /overflow-visible[\s\S]*md:overflow-y-auto/)
  assert.match(profileModal, /mt-6 w-full space-y-1/)
  assert.match(profileModal, /text-3xl font-bold tracking-wide text-brand-navy/)
  assert.match(profileModal, /text-base font-medium text-brand-gray/)
  assert.match(profileModal, /text-center text-3xl/)
  assert.match(profileModal, /text-center text-base/)
  assert.match(profileModal, /v-model="editForm\.gender"[\s\S]*text-center[\s\S]*md:text-left/)
  assert.match(profileModal, /v-model="editForm\.gender"[\s\S]*\[text-align-last:center\][\s\S]*md:\[text-align-last:left\]/)
  assert.match(profileModal, /v-model="editForm\.gender"[\s\S]*pr-0[\s\S]*md:pr-5/)
  assert.match(profileModal, /block h-9/)
  assert.match(profileModal, /block h-6/)
  assert.match(profileModal, /mx-auto[\s\S]*md:mx-0/)
  assert.match(profileModal, /h-9 py-0 leading-9/)
  assert.match(profileModal, /h-6 py-0 leading-6/)
  assert.doesNotMatch(profileModal, /isEditingProfile \? 'mt-4 space-y-0\.5' : 'mt-6 space-y-1'/)
  assert.doesNotMatch(profileModal, /isEditingProfile \? 'h-32 w-32 md:h-36 md:w-36'/)
})
